name: Node.js Gemini API Key Test

on:
  push:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Reposyu klonla
        uses: actions/checkout@v3

      - name: Node.js kur
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bağımlılıkları yükle
        run: npm install
        working-directory: server

      - name: Backend'i çalıştır
        run: node index.js
        working-directory: server
